services:
  db:
    image: postgres:16-alpine
    container_name: rodowod-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rodowod
      POSTGRES_PASSWORD: rodowod_dev
      POSTGRES_DB: rodowod
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
